project:
  type: website
  output-dir: docs
  resources:
    - img/


website:
  description: "Conversations with qwen 3.5 and Gemma 4"
  site-url: https://robertwwalker.github.io/conversations-with-qwen/ # you must change this appropriately for RSS feeds to work properly
  title: "qwen 3.5/Gemma 4 conversations"
  navbar:
    right:
      - icon: github
        href: https://github.com/robertwwalker/conversations-with-qwen
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sketchy
